### ISSUE TITLE
Timeout exceed error while executing hello-test.js using mocha

### ISSUE THREAD

**Issue by anurag308** [eris-ltd/hello-eris#10]
vivek@vivek-Latitude-3440:~/.eris/apps/hello-eris$ mocha test/hello-test.js

[2016-12-28 09:56:29.807] [INFO] [default] - Initializing LOG4JS ...
[2016-12-28 09:56:29.880] [INFO] [default] - Configuring logger for category: default, level: INFO
[2016-12-28 09:56:29.880] [INFO] [default] - Configuring logger for category: eris.wrapper, level: DEBUG

[2016-12-28 09:56:30.305] [DEBUG] eris.wrapper - Creating contract factory with ABI [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] at address 253925CB15BC36D782C5C5752EEEB512DB631313.
[2016-12-28 09:56:30.307] [DEBUG] eris.wrapper - Creating contract factory with ABI [object Object],[object Object],[object Object],[object Object],[object Object] at address undefined.

  Hello Eris Test
    1) Module Initialization
    Deals
Error callback from sendTransaction
[2016-12-28 09:56:36.057] [DEBUG] eris.hello.chain - Created new deal id: i1, buyer:John, seller: Hank, amount: 7364
      2) Add Deal

  0 passing (5s)
  2 failing

  1) Hello Eris Test Module Initialization:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) Hello Eris Test Deals Add Deal:
     AssertionError: expected [Error: No account address provided, and no default account has been set.] to be null
      at test/hello-test.js:27:36
      at js/libs/hello-chain.js:67:13
      at node_modules/eris-contracts/lib/solidity/function.js:174:13
      at DevPipe.transact (node_modules/eris-contracts/lib/pipes/dev_pipe.js:87:13)
      at SolidityFunction.sendTransaction (node_modules/eris-contracts/lib/solidity/function.js:171:16)
      at SolidityFunction.execute (node_modules/eris-contracts/lib/solidity/function.js:218:29)
      at Object.addDeal (js/libs/hello-chain.js:64:21)
      at Context.<anonymous> (test/hello-test.js:26:19)

![error mocha](https://cloud.githubusercontent.com/assets/22438763/21513912/2780b61c-cce4-11e6-8d26-e63880ef7b4f.png)

**Comment by anurag308** [comment]
Hello Guys, 
1st issue has been solved...

just add bellow statements in your hello-test.js file after this
it("Module Initialization", function(done) {

this.timeout(5000);
setTimeout(done, 3000);

thanks...

**Comment by zramsay** [comment]
thanks for the follow up @anurag308 !

**Comment by anurag308** [comment]
Hello @zramsay, I need the description of this application so that I can implement it and can explain to my friends that how blockchain is implemented in this application and how it is working...
Looking for favourable response...
thanks
